## PyTorch Tensor Allocation(파이토치 텐서 선언하기)

In [1]:
import torch
import numpy as np

### 1D with PyTorch

In [2]:
Vector = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

In [3]:
print(Vector.dim())
print(Vector.size())

1
torch.Size([7])


### 2D with PyTorch

In [4]:
Matrix = torch.FloatTensor([[1., 2., 3.], [4., 5., 6], [7., 8., 9.]])

In [5]:
print(Matrix.dim())
print(Matrix.size())

2
torch.Size([3, 3])


In [6]:
Matrix = torch.FloatTensor([[1., 2., 3.], 
                            [4., 5., 6.],
                            [7., 8., 9.],
                            [10., 11., 12]])

In [7]:
print(Matrix.dim())
print(Matrix.size())

2
torch.Size([4, 3])


### Broadcasting

In [8]:
# 같은 크기의 연산
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [9]:
#크키가 다른 Tensor들 간의 연산 #1
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)
# m2의 크기를 (1, 2)로 변경하여 연산을 수행했다.

tensor([[4., 5.]])


In [10]:
#크키가 다른 Tensor들 간의 연산 #2
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)
# m1과 m2를 2 by 2 matrix로 broadcasting하여 계산을 진행했다.

tensor([[4., 5.],
        [5., 6.]])


## 자주 사용되는 기능들

### 행렬 곱셈(내적)과 곱셈의 차이(Matrix Multiplication(dot product) Vs. Multiplication)

In [11]:
# 행렬 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1.matmul(m2))
print(m1.mul(m2)) # Broadcasting된 이후 연산이 진행된다.

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


### 평균(Mean)

In [12]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [13]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim = 0)) # 열의 차원을 보존하면서 평균을 구한 값
print(t.mean(dim = 1)) # 행의 차원을 보존하면서 평균을 구한 값
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### 덧셈(Sum)

In [14]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.sum(dim = 0)) # 열의 차원을 보존하면서 덧셈 연산
print(t.sum(dim = 1)) # 행의 차원을 보존하면서 덧셈 연산
print(t.sum(dim = -1))

tensor(2.5000)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### 최대(Max)와 아그맥스(ArgMax)

In [15]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t.max())
print(t.argmax())
print(t.max(dim = 0))

tensor(6.)
tensor(5)
torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))


### 뷰(View)

In [16]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [17]:
# 3차원 Tensor에서 2차원 Tensor로 변경

In [18]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [19]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 스퀴즈(Squeeze) - 1인 차원을 제거

In [20]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print(" ")
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
 
tensor([0., 1., 2.])
torch.Size([3])


### 언스퀴즈(Unsqueeze)

In [21]:
ft = torch.Tensor([0, 1, 2])
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)
#(3,)의 크기를 가졌던 1차원 Vector가 (1, 3)의 Matrix가 된것을 알 수 있다.(앞에서 사용한 View를 이용해서도 구현 가능하다.)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


### 타입 캐스팅(Type Casting)

In [22]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt.float())
print(lt.float().type())
print(lt.byte())
print(lt.byte().type())
print("="*50)
lt = torch.ByteTensor([1, 2, 3, 4])
print(lt.float())
print(lt.float().type())
print(lt.long())
print(lt.long().type())

tensor([1., 2., 3., 4.])
torch.FloatTensor
tensor([1, 2, 3, 4], dtype=torch.uint8)
torch.ByteTensor
tensor([1., 2., 3., 4.])
torch.FloatTensor
tensor([1, 2, 3, 4])
torch.LongTensor


### 연결하기(Concatenate)

In [23]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [24]:
print(torch.cat([x, y], dim=0))
print(" ")
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
 
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### 스택킹(Stacking)

In [25]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [26]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### ones_like 와 zeros_like

In [27]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

In [28]:
print(torch.ones_like(x))
print(" ")
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In - Place Operation(덮어쓰기 연산)

In [29]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [30]:
print(x.mul(2.))
print(x)
print(" ")
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
 
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
